import sys
import numpy as np

STANDARD_SAMPLE_WIDTH = 2
STANDARD_FRAME_RATE = 44_100
STANDARD_FORMAT = np.int16
STANDARD_CHANNELS = 1 if sys.platform == "darwin" else 2

LOWEST_AUDIBLE_FREQUENCY = 20
HIGHEST_AUDIBLE_FREQUENCY = 20_000
SPEED_OF_SOUND_IN_AIR = 344  # m/s

BASE_FREQUENCY = 440
BASE_LETTER = "A"
BASE_OCTAVE = 4
NOTES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"]
BASE_LETTER_INDEX = NOTES.index(BASE_LETTER)
